site_name: Optima Prevent
site_url: https://support.optima-prevent.eu
site_author: A1 Informatika d.o.o.
site_description: Dokumentacija in podpora za programsko opremo Optima Prevent

repo_url: https://github.com/a1info/support
repo_name: a1info/support
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides # Če boste kdaj prilagajali HTML teme
  language: sl
  logo: media/logos/op-logo.png
  favicon: media/logos/op-logo-blue.png
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  palette:
    # Svetla tema
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom # Barvo bomo določili v CSS
      accent: custom
      toggle:
        icon: material/weather-night
        name: Preklopi na temno temo
    # Temna tema
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Preklopi na svetlo temo
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.tooltips
    - content.tabs.link

extra_css:
  - assets/index.css

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - toc:
      permalink: true
      toc_depth: 3

nav:
  - Domov: index.md
  - Priročnik:
    - Uvod: introduction.md
    - Uporaba: manual-sl.md
  - FAQ in Podpora: faq-sl.md